# This is a basic workflow to help you get started with Actions

name: Prune Environments

# Controls when the workflow will run
on:
  pull_request:
    types: [ closed ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prune:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Mark environment as deactivated
        uses: bobheadxi/deployments@v1
        with:
          step: deactivate-env
          env: feature-123
          desc: Environment was pruned
