name: Issue Ops
on:
  issue_comment:
    types: [created]

jobs:
  debug_env:
    if: (github.event.issue.pull_request && startsWith(github.event.comment.body, 'run debug_env'))
    runs-on: ubuntu-latest
    steps:
      - name: Debug GITHUB_REF
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          printenv
